CREATE TABLE Users 
  ( id SERIAL PRIMARY KEY, 
  firstName VARCHAR(255) NOT NULL DEFAULT '', 
  lastName VARCHAR(255) NOT NULL DEFAULT '', 
  emailAddress VARCHAR(255) NOT NULL DEFAULT '' 
  UNIQUE, password VARCHAR(255) NOT NULL DEFAULT '', 
  createdAt TIMESTAMP NOT NULL, 
  updatedAt TIMESTAMP NOT NULL );

CREATE TABLE Courses 
  ( id SERIAL PRIMARY KEY, 
  title VARCHAR(255) NOT NULL DEFAULT '', 
  description TEXT NOT NULL DEFAULT '', 
  estimatedTime VARCHAR(255), 
  materialsNeeded VARCHAR(255), 
  createdAt TIMESTAMP NOT NULL, 
  updatedAt TIMESTAMP NOT NULL, 
  userId INTEGER NOT NULL DEFAULT -1 REFERENCES 
  Users (id) ON DELETE CASCADE ON UPDATE CASCADE );

